[project]
name = "gatekeeper"
version = "1.0.0"
description = "Default template for PDM package"
authors = [
    {name = "arekkulczycki", email = "ten.arek@gmail.com"},
]
dependencies = []
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
