services:
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
  gatekeeper:
    build:
      context: .
      dockerfile: gatekeeper/Dockerfile
    command: .venv/bin/python -m gunicorn --log-level=info -b 0.0.0.0:5000 app:app
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"  # 5000 is the flask default port
    depends_on:
      postgres:
        condition: "service_started"
        required: true
  trains:
    env_file:
      - .env.trains
    build:
      context: .
      dockerfile: trains/Dockerfile
    command: .venv/bin/python -m celery -A src.trains.app worker -c 1 -f /dev/null -Q trains
    links:
      - rabbitmq
      - postgres
    depends_on:
      rabbitmq:
        condition: "service_started"
        required: true
      postgres:
        condition: "service_started"
        required: true
  trains-scheduler:
    build:
      context: .
      dockerfile: trains/Dockerfile
    command: .venv/bin/python -m celery -A src.trains.app beat -f /dev/null -S src.trains.tasks.syncing_scheduler:SyncingScheduler
    links:
      - rabbitmq
      - postgres
    depends_on:
      rabbitmq:
        condition: "service_started"
        required: true
      postgres:
        condition: "service_started"
        required: true
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    command: .venv/bin/python -m celery -A src.controller.app worker -c 1 -f /dev/null -Q controller
    links:
      - rabbitmq
      - postgres
    depends_on:
      rabbitmq:
        condition: "service_started"
        required: true
      postgres:
        condition: "service_started"
        required: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
#  flower:
#    image: mher/flower:2.0.0
#    environment:
#      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
#      - FLOWER_PURGE_OFFLINE_WORKERS=10
#    ports:
#      - 5555:5555
#    links:
#      - rabbitmq
#    deploy:
#      restart_policy:
#        condition: on-failure
